version: "3"

services:
  mysql-container:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE:recipesMix
    networks:
      - my-network

  nodejs-container:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql-container
    networks:
      - my-network
networks:
  my-network:
